apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: unaisrashid13@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:        # Where the private key of cert lives
      name: letsencrypt-route53
    solvers:        # Validate owenership of domain when cert is issued 
    - http01:
        ingress:
          class: nginx
        
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: argo-secret
spec:
  acme:
    email: unaisrashid13@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:        # Where the private key of cert lives
      name: argo-secret
    solvers:        # Validate owenership of domain when cert is issued 
    - http01:
        ingress:
          class: nginx
    
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: grafana-secret
spec:
  acme:
    email: unaisrashid13@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:        # Where the private key of cert lives
      name: grafana-secret
    solvers:        # Validate owenership of domain when cert is issued 
    - http01:
        ingress:
          class: nginx


---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: prometheus-secret
spec:
  acme:
    email: unaisrashid13@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:        # Where the private key of cert lives
      name: prometheus-secret
    solvers:        # Validate owenership of domain when cert is issued 
    - http01:
        ingress:
          class: nginx
          
            
        