apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: unaisrashid13@gmail.com
    # server: https://acme-staging-v02.api.letsencrypt.org/directory   # Staging server
    server: https://acme-v02.api.letsencrypt.org/directory   # Production service
    privateKeySecretRef:        # Where the private key of cert lives
      name: letsencrypt-route53
    solvers:        # Validate owenership of domain when cert is issued 
    - dns01:
        route53:
          hostedZoneID: Z08062433SPGWTOR9FA3E
          region: eu-north-1 
      selector:
        dnsZones:
        - tm.nginxunais.com
    - http01:
        ingress:
          class: nginx
        
  
            
        