provider: aws

env:
- name: AWS_DEFAULT_REGION
  value: eu-north-1

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::801822495646:role/external_dns_role"

domainFilters:
  - nginxunais.com

sources:
  - ingress
  - service

policy: upsert-only
registry: txt
txtOwnerId: eks-cluster
