controller:
  replicas: 1
  service:
    type: LoadBalancer


annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
  nginx.ingress.kubernetes.io/ssl-redirect: "false" # Forces HTTPS when TLS is configured; prevents plaintext access
  cert-manager.io/cluster-issuer: letsencrypt-route53 # which cert to use, this ingress wants a cert
  service.beta.kubernetes.io/aws-load-balancer-type: alb
  service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing


    
