apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   nginx.ingress.kubernetes.io/ssl-redirect: "true" # Forces HTTPS when TLS is configured; prevents plaintext access
   cert-manager.io/cluster-issuer: argo-secret # which cert to use, this ingress wants a cert
spec:
  ingressClassName: nginx
  tls: 
  - hosts:
    - argocd.nginxunais.com
    secretName: argocd-ingress-tls # K8s tls cert created automatically: contains tls.crt – certificate and tls.key – private key
  rules:
  - host: argocd.nginxunais.com 
    http:
      paths:
      - path: /
        pathType: Prefix  # Prefix allows routing of / and any subpaths
        backend:
          service:
            name: argo-argocd-server
            port:
              number: 8080
