name: Docker push 

on:
  workflow_dispatch: 
    inputs:
        docker-push:
            description: 'Do you want to push? Type "yes" to proceed'
            type: string

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  
jobs:
  Cypress-Test:
   
  
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps: 
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          with:
            mask-password: true
          
        - name: Build and push the tagged docker image to Amazon ECR
          id: build-image
          
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: latest
          run: |
            docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.33.1
          with:
            image-ref: 801822495646.dkr.ecr.eu-north-1.amazonaws.com/eks-project:latest
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'MEDIUM'

        - name: push image to ECR 
          run: |
            docker push 801822495646.dkr.ecr.eu-north-1.amazonaws.com/eks-project:latest
